### ISSUE TITLE
No socket messages

### ISSUE THREAD

**Issue by lonnietc** [mohitwildbeast/Chat-App-Flask-SocketIO#1]
Hello,

I am a bit new to Python and Flask-SocketIO but am learning from your chat App towards a project that I want to do.

I was able to start up the chat app, but when I open 2 different browsers with different users and the same room, I do not get any messages from either the chat app about joining or from each user.

I do see this message in the run screen:

.
.
. 
127.0.0.1 - - [27/Apr/2021 13:07:22] "GET / HTTP/1.1" 200 974 0.012967
127.0.0.1 - - [27/Apr/2021 13:07:23] "GET /static/bootstrap.min.css HTTP/1.1" 200 160724 0.328171
(560) accepted ('127.0.0.1', 52616)
127.0.0.1 - - [27/Apr/2021 13:07:23] "GET /static/style.css HTTP/1.1" 200 1169 0.011967
127.0.0.1 - - [27/Apr/2021 13:07:23] "GET /favicon.ico HTTP/1.1" 404 495 0.005506
127.0.0.1 - - [27/Apr/2021 13:07:29] "POST /chat HTTP/1.1" 200 2552 0.006979
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)

Any ideas as to what is happening here?

Also, the "Leave this Chat" button does not seem to work either.

I am using Python 3.9 for this project and installed the "requirements.txt"

Can you please help?
Thanks

**Comment by msindev** [comment]
Can you use the code from GitHub repo to run and not directly from the
video, as while writing something might have been missed. Also I recommend
using a virtualenv for running the project with requirements.txt installed.

Thank you
Mohit

**Comment by lonnietc** [comment]
Hello,

Thanks for getting back to me.

I am actually using the pyCharm IDE and it runs each project in a virtualenv as well.

The code that I used was downloaded from your site directly:

[tvDemo03.zip](https://github.com/mohitwildbeast/Chat-App-Flask-SocketIO/files/6386592/tvDemo03.zip)

What is strange is that I also tested the Flask-SocketIO code from:

https://github.com/miguelgrinberg/Flask-SocketIO/tree/master/example

by taking the "example" directory and making it a project after which I ran it, then it ran just fine.

Also, what I want to do with your code is to change it a bit so that it would also need "password" field and then have a static password in you code since probably only one person will be using the code and it will be getting messages from another site via a webhook. Still need to figure out how to make a static password setup and verification before it will go to the "chat" page.

If you have any ideas on this then please let me know as well since I am new to it all.
Thanks
Lonnie

**Comment by lonnietc** [comment]
Hello,

I wanted to follow up on this to ask, if the code from the Repo word for you as perhaps I have some setting different here that is making it not work for me.

**Comment by lonnietc** [comment]
Hello Mohit,

I have had success in figuring out the problem.  It was not with the code, but with the "requirements.txt" file.

When I added versions to the file then it worked.

New "requirements.txt" should contain:

Flask==1.0.2
Flask-Session==0.3.1
Flask_SocketIO==4.3.1
eventlet

This seems to work well.
Cheers
